### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by taka-mora** [RedFlamer/Map-Based-Optimizations#1]
whenever i install this mode tha game keeps shuting down is there something im doing wrong as soon as i delete the file the game run normaly and one more thing what is the meta.json do i need to download it

**Comment by RedFlamer** [comment]
The mod is not supported for the epic games version of PAYDAY 2, otherwise if you're playing on Steam i need the crash.txt file to fix it.

**Comment by kythyria** [comment]
What does the Epic version do differently?

**Comment by taka-mora** [comment]
Ah ok i didn't know that it doesn't work with epic games
